/*
 * This source file was generated by the Gradle 'init' task
 */
package practice4;

public class Practice4 {
    public boolean divisible_3(int[] data){
        int sum = 0;
        for (int num : data){
            sum += num;
        }

        if (sum % 3 == 0){
            return true;
        }
        else{
            return false;
        }
    }
}
