/*
 * This source file was generated by the Gradle 'init' task
 */
package practice4;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class PracticeTest {
    @Test
    void notDivisible(){
        Practice4 practice = new Practice4();
        int[] data = {1, 2, 3, 4, 5, 6, 7};
        assertEquals(practice.divisible_3(data), false);
    }

    @Test
    void divisible(){
        Practice4 practice = new Practice4();
        int[] data = {1, 2, 3, 4, 5, 6};
        assertEquals(practice.divisible_3(data), true);
    }

    @Test
    void notDivisibleNeg(){
        Practice4 practice = new Practice4();
        int[] data = {-1, 2, 3, 4, 5, -6, 7};
        assertEquals(practice.divisible_3(data), false);
    }

    @Test
    void notDivisibleZero(){
        Practice4 practice = new Practice4();
        int[] data = {};
        assertEquals(practice.divisible_3(data), true);
    }
}
